### ISSUE TITLE
MultiGPU notebooks calculated differentially expressed PCAs

### ISSUE THREAD

**Issue by Intron7** [NVIDIA-Genomics-Research/rapids-single-cell-examples#99]
Hey Nvidia Genomics Team,

In the Multi GPU Notebook the AnnData object post PCA is created with the PCA in `.X`. Therefore when you later later perform the differential gene expression you calculate the which PCA is the most import for each cluster. 

The ranked gene groups function still has a couple of bugs. There is a PR with a fix. Which also introduces some performance improvements.

Yours Severin

**Comment by 111kakaluote** [comment]
I create anndata with lognormalized and scaledata, like this:  
```
sparse_gpu_array_scale = dask_sparse_arr.compute()  #sparse_gpu_array_scale store scaledata
adata = anndata.AnnData(sparse_gpu_array_scale.get())
adata.layers["normalised"] = sparse_gpu_array.get()  #sparse_gpu_array store lognormalized data
adata.var_names = genes.to_pandas()
adata.obsm['X_pca'] = local_pca.get()
```
so I can ranked gene groups with adata.X. however, which the newest verison of rapids-single-cell-example? github or docker images?
